CREATE DATABASE SP_335

SELECT * FROM MST_CITY;

SELECT * FROM MST_STATE;

---CREATE STORED PROCEDURE---

---Give proper name like PR_TableName_OperationName


---1. Select All
---CityID, CityName, Pincode, CityRemarks, StateID,
---StateName

CREATE PROCEDURE PR_MST_CITY_SELECTALL_12

		AS
		BEGIN
			SELECT		CITYID,
						CITYNAME,
						PINCODE,
						CITYREMARKS,
						MST_CITY.STATEID,
						STATENAME
		FROM MST_CITY
		INNER JOIN MST_STATE 
		ON MST_CITY.STATEID = MST_STATE.STATEID
		END

--EXEC PR_MST_CITY_SELECTALL_12


---2. Insert
CREATE PROCEDURE PR_MST_CITY_INSERT_1
		@CITYID			INT,
		@CITYNAME		VARCHAR(250),
		@PINCODE		VARCHAR(6),
		@STATEID		INT,
		@CITYREMARKS	VARCHAR(500)

		AS
		BEGIN

		INSERT INTO MST_CITY
		(
		CITYID,		
		CITYNAME,	
		PINCODE,	
		STATEID,	
		CITYREMARKS
		)
		VALUES
		(
		@CITYID,		
		@CITYNAME,	
		@PINCODE,	
		@STATEID,	
		@CITYREMARKS
		)
		END

--EXEC PR_MST_CITY_INSERT_1 5,'RAJKOT','360004',1,'THE BEST' 
			

--3. Update

CREATE PROCEDURE PR_MST_CITY_UPDATE
		@CITYID				INT,
		@CITYNAME			VARCHAR(250),
		@PINCODE			VARCHAR(6),
		@STATEID			INT,
		@CITYREMARKS		VARCHAR(500)

		AS
		BEGIN

		UPDATE MST_CITY

		SET CITYNAME = @CITYNAME,
			PINCODE = @PINCODE,
			STATEID = @STATEID,
			CITYREMARKS = @CITYREMARKS

			WHERE CITYID = @CITYID

			END;

---EXEC PR_MST_CITY_UPDATE 3,'BERLIN','360004',1,'GOOD';


---4. Delete

CREATE PROCEDURE PR_MST_CITY_DELETE

		@CITYID INT

		AS
		BEGIN

		DELETE FROM MST_CITY
		WHERE CITYID = @CITYID
		END;

---EXEC PR_MST_CITY_DELETE 3 

---5. SelectByPK

CREATE PROCEDURE PR_MST_CITY_SELECTBYPK

		@CITYID INT

		AS
		BEGIN

		SELECT * FROM MST_CITY
		WHERE CITYID  = @CITYID

		END;

---EXEC PR_MST_CITY_SELECTBYPK 4

---6. SelectByPincodeStartWith360

CREATE PROCEDURE PR_MST_CITY_PINCODESTARTSWITH360

	AS
	BEGIN

	SELECT * FROM MST_CITY

	WHERE PINCODE LIKE '360%'

	END;

---EXEC PR_MST_CITY_PINCODESTARTSWITH360 

--7. SelectByCityNamePincode

CREATE PROCEDURE PR_MST_CITY_SELECTBYCITYNAMEPINCODE

		@CITYNAME VARCHAR(250),
		@PINCODE VARCHAR(6)

		AS
		BEGIN

		SELECT * FROM MST_CITY

		WHERE CITYNAME = @CITYNAME 
			AND
				PINCODE = @PINCODE

				END;

---EXEC PR_MST_CITY_SELECTBYCITYNAMEPINCODE 'RAJKOT',360004

---8. SelectByCityRemarks

CREATE PROCEDURE MST_CITY_SELECTBYCITYREMARKS

		@CITYREMARKS VARCHAR(500)

		AS
		BEGIN

		SELECT * FROM MST_CITY
		WHERE CITYREMARKS = @CITYREMARKS

		END;
--EXEC MST_CITY_SELECTBYCITYREMARKS 'THE BEST';


---9. SelectByStateID

CREATE PROCEDURE MST_CITY_SELECTBYSTATEID

		@STATEID INT

		AS
		BEGIN

		SELECT * FROM MST_CITY

		WHERE STATEID = @STATEID

		END;

---EXEC MST_CITY_SELECTBYSTATEID 3
 
---10. SelectByStateIDCityID

CREATE PROCEDURE MST_CITY_SELECTBYSTATEIDCITYID

		@STATEID INT,
		@CITYID INT

		AS
		BEGIN

		SELECT * FROM MST_CITY

		WHERE STATEID = @STATEID AND CITYID = @CITYID

		END;

---EXEC MST_CITY_SELECTBYSTATEIDCITYID 1,1
				
